### ISSUE TITLE
New responsive material-ui

### ISSUE THREAD

**Issue by sj-louw** [denvera/dsc-node#4]
@denvera As part of learning ReactJS, I have written a mobile friendly (responsive) React (Material-UI) frontend clone of this app. Unfortunately I have not integrated it with the server code, so some changes will have to be made for integration. Not sure what this would involve. 

Anyway, if you're interested, here is the code:
[https://github.com/sj-louw/dsc-react](https://github.com/sj-louw/dsc-react)

<a href="https://raw.githubusercontent.com/sj-louw/dsc-react/master/screenshots/keypad.png">
<img src="https://raw.githubusercontent.com/sj-louw/dsc-react/master/screenshots/keypad.png">
</a>

**Comment by denvera** [comment]
Hi @sj-louw, this looks great, thank you! I'll see what can be done to integrate it, its far better than my attempt at a UI!
